version: '3.8'

services:
  uaifood:
    build: '.'
    container_name: uaifood.web
    ports:
      - ${LISTEN_PORT}:${LISTEN_PORT}
    volumes:
      - .:/app
    links:
      - postgresql
      - redis
    depends_on:
      - postgresql
      - redis

  postgresql:
    image: postgis/postgis
    # build:
     # context: ./
      # dockerfile: ./Dockerfile.postgres
    container_name: uaifood.postgres
    ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

  redis:
    container_name: uaifood.redis
    image: redis:6-alpine
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
        - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
        - redisdata:/data

volumes:
  postgresdata:
  redisdata:
